### ISSUE TITLE
Populate the wiki home page

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/boreholeie#1]
Need to set this up

**Comment by denevers** [comment]
No "edit" button on wiki page. restricted ?

**Comment by ollieraymond** [comment]
+1

Do we have to be invited to join the github repository as contributors? My username is ollieraymond

**Comment by sgrellet** [comment]
@denevers : I added you to BoreholeIE team, you should now be able to edit the wiki.
@ollieraymond  : have you associated your GitHub id with the IE (that will also associate it with OGC organisation). Otherwise, I find you but cannot edit ('is not member of the organization')

**Comment by PeterWarren** [comment]
could you please add me? I cant get the association to work.

**Comment by sgrellet** [comment]
@PeterWarren  : should be ok now.

**Comment by John-Sharples** [comment]
@sgrellet: great if you could add me too. Thanks

**Comment by sgrellet** [comment]
@John-Sharples : should be ok

**Comment by daoane** [comment]
No edit button on the wiki for me, but otherwise the repro seems to be open (i.e. OGC association seems to work).

**Comment by sgrellet** [comment]
Now you can :)

**Comment by sgrellet** [comment]
Works now for daoane
