### ISSUE TITLE
Formalise vocabulary for defining position of borehole elements

### ISSUE THREAD

**Issue by denevers** [opengeospatial/boreholeie#22]
Good presentation here 

https://dl.ppdm.org/dl/109

Need to formalise 'elevation', 'height' and 'depth'

**Comment by mbeaufils** [comment]
According to ISO 6709 and ISO 19111: https://www.sis.se/api/document/preview/910055/

Altitude :  "height where the chosen reference surface is mean sea level"

Height : "distance of a point from a chosen reference surface measured upward along a line perpendicular to that surface"

Depth : "distance of a point from a chosen reference surface measured downward along a line perpendicular to that surface."

**Comment by denevers** [comment]
Right, We need to include this in the conceptual model as different elements in a borehole can be positionned using any of those concepts

**Comment by mbeaufils** [comment]
You mean #21 ?

**Comment by denevers** [comment]
yes, fixed it, thanks

**Comment by mbeaufils** [comment]
Agreeing first on those vocabs is not a bad idea. It would ensure that we understand the same things in #21.

**Comment by mbeaufils** [comment]
Regarding the ISO 19111 definition :

"Depth" is the opposite of "Height" and mention a reference surface.

If we agree on ISO 19111 definition, then "Depth" shall not be used to define a position along our borehole trajectory.

**Comment by denevers** [comment]
Also, depth is linear (along gravity ?).  We need another work to define distance along borehole.
(in perfectly vertical borehole, both concept overlaps)

**Comment by mbeaufils** [comment]
Yes in perfectly vertical boreholes this is the same > we shall limit to that use case :-)

+1 to have a dedicated github issue for distance along borehole

**Comment by sgrellet** [comment]
This is most of all what we end up doing in the IE (with BhML)
