### ISSUE TITLE
UC13: positioning

### ISSUE THREAD

**Issue by daoane** [opengeospatial/boreholeie#26]
UC13 Analysis on core & result positionning down the hole

A description of the positioning system for the measurements on the core is missing. Without it, the UC task "result positioning down the hole" will not be possible to achieve.

It might be worth to compare a solution for result positioning on the core that itself is positioned down the hole with one that directly converts core positions to "down the hole" positions.
Core measurements are not downhole logs, and the question is at what stage it is most meaningful to do the depth conversion. If core measurements are kept on the core and only converted to "down the hole" positions when it is necessary, then they will follow along the core in case the core is repositioned along the borehole, e.g. through the comparison of downhole logs with geophysical core logs (which also requires data on the core, and not converted to "down the hole" depth).

**Comment by denevers** [comment]
let's us dust off some work from Simon

https://www.seegrid.csiro.au/wiki/Xmml/BoreHole#Borehole_survey

(XMML is the ancestor of O&M and GeoSciML)

**Comment by daoane** [comment]
The linked document describes measurements along a borehole. What we need is measurements along a drill core and how the depth-on-core relates to the borehole depth (it's all about conventions, in this case, how it is done at CSIRO; see also UC14 for how it is done at ICDP).

**Comment by sgrellet** [comment]
We could do linear referencing on the core itself (same mechanics as in BhML but with the Core)
