### ISSUE TITLE
Change type for at and from/to to allow ‘measure’ and ‘boreholeEvent’

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/boreholeie#41]
From Leuven physical meeting
Change type for at and from/to to allow ‘measure’ and ‘boreholeEvent’ (union) -> remove FromToEvent class (but reuse part of the def of FromToEvent)

**Comment by sgrellet** [comment]
done in BhML Model - rev 14

**Comment by denevers** [comment]
rename measure:Measurement to distanceAlong:Measurement in MeasureOrEvent Union ?

**Comment by sgrellet** [comment]
Yes. agreed in webconf 24 and implemented in BhML Model - rev 18
