### ISSUE TITLE
Borehole Coordinate System Concept to reuse

### ISSUE THREAD

**Issue by mbeaufils** [opengeospatial/boreholeie#46]
For now, there is a connection between BoreholeEventCollection and TrajectoryReferent.

This means that we can define the point that is used as the origin for the distanceexpression.
Yet, two BoreholeEventCollections having the same TrajectoryReferent + same distanceexpression may not be similar. There may be for example conventions in which depth are measured with positive values, and in some with negative values.

I propose to have a concept that would be a joint of :
- Borehole trajectory,
- TrajectoryReferent,
- LinearReferencingMethod.

This is basically the definition of Coordinate Referencing System (CRS).

BoreholeCRS would have an Id.
BoreholeEventCollection would then be linked to BoreholeCRS, and not TrajectoryReferent.

**Comment by sgrellet** [comment]
Makes sense but still needs some refinements to be sure I got you right
- 'joint' being implemented using just basic asociation or other ? 
- 'There may be for example conventions in which depth are measured with positive values, and in some with negative values.' -> not sure it is possible with our current model.
see TrajectoryReferent --1>TrajectoryPosition --1->BoreholeReferencingMethod + recent update on MeasureOrEvent:distanceAlong ("...The measure is done according to the BoreholeReferencingMethod to which the TrajectoryReferent is related.) May then need to revisit things there also (ex : add this BoreholeCRS in the def instead)

**Comment by sgrellet** [comment]
sorry closed unwilingly

**Comment by mbeaufils** [comment]
Would be basic association for me. Attached is a sketch of proposed model.
![BhML_rev18+proposal](https://user-images.githubusercontent.com/17067226/60971281-12bc6f00-a324-11e9-87cb-9ac575479624.jpg)

**Comment by sgrellet** [comment]
ok. just wondering whether flipping +referentPoint, +rm and +trajectory associations would make better sense.

**Comment by sgrellet** [comment]
uploading tentative model change after webconf 26 and discussion with Mickaël
![20190729_BoreholeCRS](https://user-images.githubusercontent.com/16756304/62058618-09873980-b222-11e9-8ac9-ed09ffe804d0.png)

**Comment by sgrellet** [comment]
discussed and elaborated during webconf 27
done in BhML Model - rev 35
