### ISSUE TITLE
AtLocation:atLocation -> atPosition

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/boreholeie#58]
In 19148 the class 'AtLocation'  contains a 'atPosition' attribute. 
We mimicked that pattern for the FromToLocation class (which contains fromPosition/toPosition attributes) but not here. 

Should be fixed before the ER -> also implies instances update.

**Comment by denevers** [comment]
bundle a list of last minute changes for next week meeting for discussion so we alter all our instances in one pass ?

**Comment by sgrellet** [comment]
Would be my guess yes. So that we have a kind of 'check-list' to apply. Currently giving checking all the missing def/description in the ER G.doc Helps spotting such things.

**Comment by sgrellet** [comment]
fixed in 0.3.0 (in https://github.com/opengeospatial/boreholeie/commit/5f72028f4df5bc5a808f75b1420f3e284ca9eb85)
