### ISSUE TITLE
GSC_BoisvertMichaud.xml needs update on contactType

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/boreholeie#59]
working on the conversion to RESQML we would need slight adjustments
- <swe:identifier>http://resource.geosciml.org/classifier/cgi/contacttype/0012</swe:identifier>
should point to http://resource.geosciml.org/classifier/cgi/contacttype/faulted_contact (which derefferences)
- ideally would be good to have next to the swe:identifier / swe:label (the prefLabel in CGI Geoscience vocab). for example : <swe:label>faulted contact<swe:label>

**Comment by denevers** [comment]
done commit da952db3b25e0411eff64c23eaac34987c69b631
