### ISSUE TITLE
How to encode TrajectoryReferent

### ISSUE THREAD

**Issue by bsimons14** [opengeospatial/boreholeie#68]
There are two diagrams supposedly clarifying how to encode TrajectoryReferent:

1.  https://github.com/opengeospatial/boreholeie/blob/master/Relevant_material/referent.pptx

2. https://github.com/denevers/boreholeie/blob/d9e9e700d825a62880291b752051a106d511ac05/instances/cases/bh_reference.svg

It is still unclear how these should be encoded. An option for the first (with alternative encoding as comments) is provided at:
https://github.com/opengeospatial/boreholeie/blob/master/Relevant_material/TrajectoryReferent_test.xml
What is the correct encoding?

**Comment by denevers** [comment]
My understanding was it's still under debate - hence the two proposals

**Comment by sgrellet** [comment]
Agree. Let's rediscuss it today (24th) during the webconf. One option on the table being not to carve this in the model but defer this to the BoreholeReferencingMethod (now, we have at least 2 : absolute or relative). Which seems more ISO 19148 spirit

**Comment by bsimons14** [comment]
Only one way in my example encoding can be right, but I don't know which. If they are both valid then there is no way of knowing what the depths are.


Cheers
Bruce

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by sgrellet** [comment]
I think there is a way, provided you document in the BoreholeReferencingMethod that yours is : absolute or relative (to the Referent) and the unit which is used

**Comment by bsimons14** [comment]
I've specified 'relative' but it is still not clear to me how to encode it based on the reference .ppt diagram:

    <BhML:trajectoryReferent>​
     <BhML:DistanceExpression>​
      <BhML:distanceAlong uom="http://qudt.org/vocab/unit/M">-1.0</BhML:distanceAlong>​
      

To be clear I think we need an example of each (absolute and relative) wrt the .ppt, stating what the reference point (TrajectoryReferent) is for each.

Cheers
Bruce Simons
+61 475 954 391
Grand Maître, Fêlés du Grand Colombier (#1681)
Club des Cinglés du Mont-Ventoux (#12000)
________________________________

**Comment by sgrellet** [comment]
Closing after webconference 35 (see drawing updated during the discussion)
![referent_20191024](https://user-images.githubusercontent.com/16756304/67685360-38ce5380-f995-11e9-9df7-1921c3096248.png)
